function srm

% srm.m
% Jeremy Barnes, 29/9/1999
% $Id$

global EPSFILENAME

display_results('boost-50samples', 'testtrain', ...
		'noisevalues',      0.2, ...
		'rows',             1, ...
		'cols',             1, ...
		'axis_function',    'setup_axis', ...
		'figure_function',  'setup_figure', ...
		'train_err_style',  'k--', ...
		'test_err_style',   'k-', ...
		'grid',             'off', ...
		'title',            '', ...
		'show_minimum',     1);

xlabel('|\itH|');
ylabel('Risk');

text(300, 0.3, '\it{R_{\rm{test}}}', 'fontname', 'times');
text(40, 0.1, '\it{R_{\rm{emp}}}', 'fontname', 'times');

set(1, 'paperposition', [0 0 6 2.5]);

print(EPSFILENAME, '-f1','-deps2');

