function training_curves_boost

% training_curves_boost.m
% Jeremy Barnes, 19/10/1999
% $Id$

global EPSFILENAME

display_results('boost-50samples', 'testtrain', ...
		'rows', 1, ...
		'cols', 1, ...
		'title', '(%l) \sl{AdaBoost}', ...
		'noisevalues', 0.3, ...
		'y_range', [0 0.5], ...
		'axis_function', 'setup_axis', ...
		'figure_function', 'setup_figure', ...
		'test_err_style', 'k-', ...
		'train_err_style', 'k:', ...
		'squareaxis', 0, ...
		'startletter', 'g');

set(1, 'paperposition', [0 0 6 2.5]);

print(EPSFILENAME, '-f1','-deps2');

