# Makefile for MATLAB repository
#
# Causes the mex script to be run on all appropriate files
#
# Expects "mex" to be on teh current path
#
# Makefile
# Jeremy Barnes, 20/8/1999
# $Id$

.PHONY : all

all:
	$(MAKE) -C ml_toolbox

# For some stupid reason this doesn't work...