function s = treesize(obj)

% TREESIZE return the size of the tree generated by CART
%
% SYNTAX:
%
% s = treesize(obj)
%
% RETURNS:
%
% The number of terminal nodes in the tree of the CART object OBJ.

% treesize.m
% Jeremy Barnes, 15/4/1999
% $Id$

% PRECONDITIONS:
% none

if (isa(obj.tree, 'double'))
   s = 1;
else
   s = obj.tree.size;
end

% POSTCONDITIONS:
check_invariants(obj);

