"Usage: %s [options] command [command ...]\n"
"\n"
"Options:\n"
" -q, --quiet		Be quiet (don't print anything)\n"
" -b=size, --output-buffer-size=size\n"
"			Set the size of the buffer for MATLAB output (64k)\n"
" -f name, --run-file name\n"
"			Run commands from the file `name' sequentially\n"
" -c name, --run-command name\n"
"			Run the command `name'\n"
